### PR TITLE
exposed doxygen options EXCLUDE_PATTERNS and FILE_PATTERNS to the ins…

### PR DESCRIPTION
**Pull request by leiradel**
…pector

My project has a large number of Objective-C headers with the `.h` extension, but I only need to bind things in `.hpp` headers which have C++ code, so I've exposed the `FILE_PATTERNS` option.

Moreover, I use boost and I needed to exclude its headers from the bindings, so I've also exposed the `EXCLUDE_PATTERNS` option.

My editor is configured to remove white space at the end of lines, so I'm sorry for the `Doxyfile` diff. Let me know if it's a problem for you.

### CODE REVIEW

**Comment by gaspard** [comment]
Hi there !

Thanks for these changes :-)

Let's see if I can fix the tests triggered by adding ".H" to Doxyfile first (tests are currently failing on master) and then pull in your changes.

**Comment by leiradel** [comment]
No problem. I'll make another PR to add support for some STL classes I need. My idea is to check for types `std::vector< ... >` and add them as if they were user-defined classes, including all the public methods.

Is this a good approach, or should I look somewhere else?

**Comment by gaspard** [comment]
I haven't had my head deep in dub for some time, but I think the fastest route would be to create a "VectorSomething" pseudo-header with the methods you need and then simply add a typedef in your real header (the one that will compile with the bindings).

**Comment by leiradel** [comment]
I'm not sure how to implement what you said, but I have many projects and tenths of headers per project, so I need to generate the binds automatically, i.e. without having to create/configure things per class as needed.

Thanks for the suggestion though.

**Pull request merged**
